publications/urls.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.urls import path

try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url

from publications import views

app_name = 'publications'
urlpatterns = [
    path('references/add/', views.ReferenceCreateView.as_view(), name='reference_add'),
    path('references/<int:pk>/', views.ReferenceDetailView.as_view(), name='reference_detail'),
    path('references/<int:pk>/update/', views.ReferenceUpdateView.as_view(), name='reference_update'),

    path('add/', views.PublicationCreateView.as_view(), name='publication_add'),
    path('authors/<str:name>/', views.author, name='author'),

    path('<str:citekey>/update/', views.PublicationUpdateView.as_view(), name='publication_update'),
    path('<str:citekey>/bibtex/', views.PublicationBibtexView.as_view(), name='publication_bibtex'),
    path('<str:citekey>/ris/', views.PublicationRISView.as_view(), name='publication_ris'),
    path('<str:citekey>/', views.PublicationDetailView.as_view(), name='publication_detail'),
    path("", views.year, name='publication_list'),

    url(r'^year/(?P<year>\d+)/$', views.year, name='year'),
    url(r'^tag/(?P<keyword>.+)/$', views.keyword, name='keyword'),
    url(r'^list/(?P<list>.+)/$', views.list, name='list'),
    url(r'^unapi/$', views.unapi, name='unapi'),
]

publications/models/list.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from django.db import models

class List(models.Model):
	"""
	Model representing a list of publications.
	"""

	class Meta:
		app_label = 'publications'
		ordering = ('list',)
		verbose_name_plural = 'Lists'

	list = models.CharField(max_length=128)
	description = models.CharField(max_length=128)

	def __unicode__(self):
		return self.list

	def __str__(self):
		return self.list

publications/models/publication.py
# -*- coding: utf-8 -*-

__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

import os
import re

from django.db import models
from django.utils.http import urlquote_plus
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify

from publications.fields import PagesField
from publications.models import Type, List
from string import ascii_uppercase

from django.core.validators import RegexValidator

if 'django.contrib.sites' in settings.INSTALLED_APPS:
	from django.contrib.sites.models import Site

doi_validator = RegexValidator(
	regex=r'^10.\d{4,9}\/[\-._;()\/:A-Z0-9a-z]+$',
	message='Invalid DOI.',
	code='invalid_doi',
)

class Publication(models.Model):
	"""
	Model representing a publication.
	"""

	class Meta:
		app_label = 'publications'
		ordering = ['-year', '-month', '-id']
		verbose_name_plural = ' Publications'

	# names shown in admin area
	MONTH_CHOICES = (
			(1, 'January'),
			(2, 'February'),
			(3, 'March'),
			(4, 'April'),
			(5, 'May'),
			(6, 'June'),
			(7, 'July'),
			(8, 'August'),
			(9, 'September'),
			(10, 'October'),
			(11, 'November'),
			(12, 'December')
		)

	# abbreviations used in BibTex
	MONTH_BIBTEX = {
			1: 'Jan',
			2: 'Feb',
			3: 'Mar',
			4: 'Apr',
			5: 'May',
			6: 'Jun',
			7: 'Jul',
			8: 'Aug',
			9: 'Sep',
			10: 'Oct',
			11: 'Nov',
			12: 'Dec'
		}

	type = models.ForeignKey(Type, on_delete=models.CASCADE)
	citekey = models.CharField(max_length=512, blank=True, null=True,
		help_text='BibTex citation key. Leave blank if unsure.')
	title = models.CharField(max_length=512)
	authors = models.CharField(max_length=2048,
		help_text='List of authors separated by commas or <i>and</i>.')
	year = models.PositiveIntegerField()
	month = models.IntegerField(choices=MONTH_CHOICES, blank=True, null=True)
	journal = models.CharField(max_length=256, blank=True)
	journal_abbreviation = models.CharField(max_length=256, blank=True)
	book_title = models.CharField(max_length=256, blank=True, help_text="If this work is book section, the title of the larger work.")
	publisher = models.CharField(max_length=256, blank=True)
	location = models.CharField(max_length=256, blank=True, help_text="The location where this work was published.")
	institution = models.CharField(max_length=256, blank=True, help_text="If this work is a thesis, the institution where it was completed.")
	volume = models.IntegerField(blank=True, null=True)
	number = models.IntegerField(blank=True, null=True, verbose_name='Issue number')
	pages = PagesField(max_length=32, blank=True, help_text="The full range of pages of this work if it is not a complete book.")
	note = models.CharField(max_length=256, blank=True)
	keywords = models.CharField(max_length=256, blank=True,
		help_text='List of keywords separated by commas.')
	url = models.URLField(blank=True, verbose_name='URL',
		help_text='Link to PDF or journal page.')
	code = models.URLField(blank=True,
		help_text='Link to page with code.')
	pdf = models.FileField(upload_to='publications/', verbose_name='PDF', blank=True, null=True)
	media_public = models.BooleanField(default=False, help_text='Whether or not any media files for this publication should be accessible publicly.')
	image = models.ImageField(upload_to='publications/images/', blank=True, null=True)
	thumbnail = models.ImageField(upload_to='publications/thumbnails/', blank=True, null=True)
	doi = models.CharField(
		max_length=128, 
		verbose_name='DOI', 
		blank=True, 
		validators=[doi_validator,],
	)
	external = models.BooleanField(default=False,
		help_text='If publication was written in another lab, mark as external.')
	abstract = models.TextField(blank=True)
	isbn = models.CharField(max_length=32, verbose_name="ISBN", blank=True,
		help_text='Only for a book.') # A-B-C-D
	lists = models.ManyToManyField(List, blank=True)

	def __init__(self, *args, **kwargs):
		models.Model.__init__(self, *args, **kwargs)

		# post-process keywords
		self.keywords = self.keywords.replace(';', ',')
		self.keywords = self.keywords.replace(', and ', ', ')
		self.keywords = self.keywords.replace(',and ', ', ')
		self.keywords = self.keywords.replace(' and ', ', ')
		self.keywords = [s.strip().lower() for s in self.keywords.split(',')]
		self.keywords = ', '.join(self.keywords).lower()

		self._produce_author_lists()

	def get_absolute_url(self):
		return reverse("publications:publication_detail", kwargs={"citekey": self.citekey})

	def get_absolute_update_url(self):
		return reverse("publications:publication_update", kwargs={"citekey": self.citekey})

	def _produce_author_lists(self):
		"""
		Parse authors string to create lists of authors.
		"""

		# post-process author names
		self.authors = self.authors.replace(', and ', ', ')
		self.authors = self.authors.replace(',and ', ', ')
		self.authors = self.authors.replace(' and ', ', ')
		self.authors = self.authors.replace(';', ',')

		# list of authors
		self.authors_list = [author.strip() for author in self.authors.split(',')]

		# simplified representation of author names
		self.authors_list_simple = []

		# author names represented as a tuple of given and family name
		self.authors_list_split = []

		# tests if title already ends with a punctuation mark
		self.title_ends_with_punct = self.title[-1] in ['.', '!', '?'] \
			if len(self.title) > 0 else False

		suffixes = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', "Jr.", "Sr."]
		prefixes = ['Dr.']
		prepositions = ['van', 'von', 'der', 'de', 'den']

		# further post-process author names
		for i, author in enumerate(self.authors_list):
			if author == '':
				continue

			names = author.split(' ')

			# check if last string contains initials
			if (len(names[-1]) <= 3) \
				and names[-1] not in suffixes \
				and all(c in ascii_uppercase for c in names[-1]):
				# turn "Gauss CF" into "C. F. Gauss"
				names = [c + '.' for c in names[-1]] + names[:-1]

			# number of suffixes
			num_suffixes = 0
			for name in names[::-1]:
				if name in suffixes:
					num_suffixes += 1
				else:
					break

			# abbreviate names
			names_abbreviated = names.copy()
			for j, name in enumerate(names_abbreviated[:-1 - num_suffixes]):
				# don't try to abbreviate these
				if j == 0 and name in prefixes:
					continue
				if j > 0 and name in prepositions:
					continue

				if (len(name) > 2) or (len(name) and (name[-1] != '.')):
					k = name.find('-')
					if 0 < k + 1 < len(name):
						# take care of dash
						names_abbreviated[j] = name[0] + '.-' + name[k + 1] + '.'
					else:
						names_abbreviated[j] = name[0] + '.'

			if len(names):
				self.authors_list[i] = ' '.join(names)

				# create simplified/normalized representation of author name
				if len(names) > 1:
					for name in names_abbreviated[0].split('-'):
						name_simple = self.simplify_name(' '.join([name, names_abbreviated[-1]]))
						self.authors_list_simple.append(name_simple)
				else:
					self.authors_list_simple.append(self.simplify_name(names_abbreviated[0]))

				# number of prepositions
				num_prepositions = 0
				for name in names:
					if name in prepositions:
						num_prepositions += 1

				# splitting point
				sp = 1 + num_suffixes + num_prepositions
				self.authors_list_split.append(
					(' '.join(names[:-sp]), ' '.join(names[-sp:])))

		# list of authors in BibTex format
		self.authors_bibtex = ' and '.join(self.authors_list)

		# overwrite authors string
		if len(self.authors_list) > 2:
			self.authors = ', and '.join([
				', '.join(self.authors_list[:-1]),
				self.authors_list[-1]])
		elif len(self.authors_list) > 1:
			self.authors = ' and '.join(self.authors_list)
		else:
			self.authors = self.authors_list[0]


	def __unicode__(self):
		return self.__str__()


	def __str__(self):
		if len(self.title) < 64:
			return self.title
		else:
			index = self.title.rfind(' ', 40, 62)

			if index < 0:
				return self.title[:61] + '...'
			else:
				return self.title[:index] + '...'


	def keywords_escaped(self):
		return [(keyword.strip(), urlquote_plus(keyword.strip()))
			for keyword in self.keywords.split(',')]


	def authors_escaped(self):
		return [(author, author.lower().replace(' ', '_'))
			for author in self.authors_list]


	def key(self):
		if not self.authors:
			title_slug = slugify(self.title)
			key = f"{title_slug}-{self.year}"
			assert Publication.objects.filter(citekey=key).exclude(id=self.id).count() == 0
			return key

		# this publication's first author
		author_lastname = self.authors_list[0].split(' ')[-1]

		publications = Publication.objects.filter(
			year=self.year,
			authors__icontains=author_lastname).order_by('month', 'id')

		# character to append to BibTex key
		char = ord('a')

		# augment character for every publication 'before' this publication
		for publication in publications:
			if publication == self:
				break
			if publication.authors_list[0].split(' ')[-1] == author_lastname:
				char += 1

		return self.authors_list[0].split(' ')[-1] + str(self.year) + chr(char)


	def title_bibtex(self):
		return self.title.replace('%', r'\%')


	def month_bibtex(self):
		return self.MONTH_BIBTEX.get(self.month, '')


	def month_long(self):
		for month_int, month_str in self.MONTH_CHOICES:
			if month_int == self.month:
				return month_str
		return ''


	def first_author(self):
		return self.authors_list[0]


	def journal_or_book_title(self):
		if self.journal:
			return self.journal
		else:
			return self.book_title

	def first_page(self):
		return PagesField.split(self.pages)[0]

	def last_page(self):
		return PagesField.split(self.pages)[-1]


	def z3988(self):
		contextObj = ['ctx_ver=Z39.88-2004']

		if 'django.contrib.sites' in settings.INSTALLED_APPS:
			domain = Site.objects.get_current().domain
		else:
			domain = 'example.com'

		rfr_id = domain.split('.')

		if len(rfr_id) > 2:
			rfr_id = rfr_id[-2]
		elif len(rfr_id) > 1:
			rfr_id = rfr_id[0]
		else:

publications/models/reference.py
__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Robert Turnbull <rob@robturnbull.com>'
__docformat__ = 'epytext'

from django.db import models

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse

from .publication import Publication


class Reference(models.Model):
    """ A link between a Django model object of any type and a publication. """
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    locator = models.CharField(max_length=255, default="", blank=True, help_text="The location in the publication for this reference (i.e. the page number).")

    # See https://docs.djangoproject.com/en/3.1/ref/contrib/contenttypes/
    # https://simpleisbetterthancomplex.com/tutorial/2016/10/13/how-to-use-generic-relations.html
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    def __str__(self):
        return f"{self.content_object} -> {self.publication} @ {self.locator}"

    def publication_with_locator(self):
        return f"{self.publication}, {self.locator}."

    def get_absolute_url(self):
        return reverse('publications:reference_detail', kwargs={"pk": self.pk})

    def get_absolute_update_url(self):
        return reverse('publications:reference_update', kwargs={"pk": self.pk})

    class Meta:
        ordering = ["publication__year", "publication__authors", "locator"]

publications/views/author.py
# -*- coding: utf-8 -*-

__license__ = 'MIT License <http://www.opensource.org/licenses/mit-license.php>'
__author__ = 'Lucas Theis <lucas@theis.io>'
__docformat__ = 'epytext'

from collections import defaultdict
from django.shortcuts import render
from string import capwords

from publications.models import Type, Publication, CustomLink, CustomFile
from publications.utils import populate


def author(request, name):
    fullname = capwords(name.replace('+', ' ').replace('_', ' '))
    fullname = fullname.replace(' Von ', ' von ').replace(' Van ', ' van ')
    fullname = fullname.replace(' Der ', ' der ')

    # take care of dashes
    off = fullname.find('-')
    while off > 0:
        off += 1
        if off <= len(fullname):
            fullname = fullname[:off] + fullname[off].upper() + fullname[off + 1:]
        off = fullname.find('-', off)

    # split into forename, middlenames and surname
    names = name.replace(' ', '+').replace('_', '+').split('+')

    # construct a liberal query
    surname = names[-1]
    surname = surname.replace(u'ä', u'%%')
    surname = surname.replace(u'ae', u'%%')
    surname = surname.replace(u'ö', u'%%')
    surname = surname.replace(u'oe', u'%%')
    surname = surname.replace(u'ü', u'%%')
    surname = surname.replace(u'ue', u'%%')
    surname = surname.replace(u'ß', u'%%')
    surname = surname.replace(u'ss', u'%%')

    table = Publication._meta.db_table
    query_str = f'SELECT * FROM {table} ' \
                f'WHERE lower({table}.authors) LIKE lower(%s) ' \
                f'ORDER BY {table}.year DESC, {table}.month DESC, {table}.id DESC'
    import logging
    logging.error(query_str)
    query = Publication.objects.raw(query_str, ["%"+surname+"%"])

    # find publications of this author
    publications = []
    publications_by_type = defaultdict(lambda: [])

    # further filter results
    if len(names) > 1:
        name_simple = Publication.simplify_name(names[0][0] + '. ' + names[-1])
        for publication in query:
            if name_simple in publication.authors_list_simple:
                publications.append(publication)
                publications_by_type[publication.type_id].append(publication)

    elif len(names) > 0:
        for publication in query:
            if Publication.simplify_name(names[-1].lower()) in publication.authors_list_simple:
                publications.append(publication)
                publications_by_type[publication.type_id].append(publication)

    # attach publications to types
    types = Type.objects.filter(id__in=publications_by_type.keys())
    for t in types:
        t.publications = publications_by_type[t.id]

    if 'plain' in request.GET:
        return render(request, 'publications/publications.txt', {
            'publications': publications
        }, content_type='text/plain; charset=UTF-8')

    if 'bibtex' in request.GET:
        return render(request, 'publications/publications.bib', {
            'publications': publications
        }, content_type='text/x-bibtex; charset=UTF-8')

    if 'mods' in request.GET:
        return render(request, 'publications/publications.mods', {
            'publications': publications
        }, content_type='application/xml; charset=UTF-8')

    if 'ris' in request.GET:
        return render(request, 'publications/publications.ris', {
            'publications': publications
        }, content_type='application/x-research-info-systems; charset=UTF-8')

    if 'rss' in request.GET:
        return render(request, 'publications/publications.rss', {
            'url': 'http://' + request.get_host() + request.path,
            'author': fullname,
            'publications': publications
        }, content_type='application/rss+xml; charset=UTF-8')

    # load custom links and files
    populate(publications)

    return render(request, 'publications/author.html', {
        'publications': publications,
        'types': types,
        'author': fullname
    })

publications/templates/publications/author.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="alternate" type="application/rss+xml" title="RSS" href="?rss" />
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>
{% endblock %}

{% block content %}
<div class="publications-container">
	<h1>{{ author }}</h1>

	{% if publications %}
		<div class="special_links">
			<p>
				<a href="?plain">Plain text</a>,
				<a href="?ris">RIS</a>,
				<a href="?bibtex">BibTex</a>
			</p>
		</div>
		{% for type in types %}
			<h2>{{ type.description }}{% if forloop.first %}{% endif %}</h2>
			<ul>
				{% for publication in type.publications %}
					<li>
						{% include "publications/publication.html" %}
					</li>
				{% endfor %}
			</ul>
		{% endfor %}
	{% else %}
		<p>No publications found for {{ author }}.</p>
	{% endif %}
</div>
{% endblock %}

publications/templates/publications/id.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>

	{% for publication in publications %}
		<meta name="citation_date" content="{{ publication.year }}" />
		<meta name="citation_title" content="{{ publication.title }}" />{% for author in publication.authors_list %}
		<meta name="citation_author" content="{{ author }}" />{% endfor %}{% if publication.journal %}
		<meta name="citation_journal_title" content="{{ publication.journal }}" />{% endif %}{% if publication.volume %}
		<meta name="citation_volume" content="{{ publication.volume }}" />{% endif %}{% if publication.issue %}
		<meta name="citation_issue" content="{{ publication.issue }}" />{% endif %}{% if publication.pdf %}
		<meta name="citation_pdf_url" content="{{ MEDIA_URL }}{{ publication.pdf }}" />{% endif %}{% if publication.doi %}
		<meta name="citation_doi" content="{{ publication.doi }}"/>{% endif %}{% if publication.publisher %}
		<meta name="citation_publisher" content="{{ publication.publisher }}"/>{% endif %}{% if publication.institution %}
		<meta name="citation_technical_report_institution" content="{{ publication.institution }}"/>{% endif %}{% if publication.first_page %}
		<meta name="citation_firstpage" content="{{ publication.first_page }}"/>{% endif %}{% if publication.last_page %}
		<meta name="citation_lastpage" content="{{ publication.last_page }}"/>{% endif %}
	{% endfor %}
{% endblock %}

{% block content %}
	<div class="special_links">
		<a href="?plain">Plain text</a>,
		<a href="?ris">RIS</a>,
		<a href="?bibtex">BibTex</a>
	</div>
	{% for publication in publications %}
		<h1>Publication</h1>
		<hr/>
		<div style="margin-bottom: 30px;">
		{% include "publications/publication.html" %}<br/>
		</div>
		<h1>Reference</h1>
		<hr/>
		<pre lang="bibtex">{% include "publications/publication.bib" %}</pre>
	{% endfor %}
{% endblock %}

publications/templates/publications/keyword.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>
{% endblock %}

{% block content %}
	{% if publications %}
		<div class="special_links">
			<a href="?plain">Plain text</a>,
			<a href="?ris">RIS</a>,
			<a href="?bibtex">BibTex</a>
		</div>
		<h1>Publications with the keyword &quot;{{ keyword }}&quot;</h1>
		<hr/>
		{% for publication in publications %}
			<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
				{% include "publications/publication.html" %}
			</div>
		{% endfor %}
	{% else %}
		<h2>Sorry,</h2>
		no publications found with the keyword &quot;{{ keyword }}&quot;.
	{% endif %}
{% endblock %}

publications/templates/publications/list.html
{% extends "base.html" %}

{% block head %}
	{{ block.super }}
	<link rel="unapi-server" type="application/xml" title="unAPI" href="{% url 'publications:unapi' %}"/>
{% endblock %}

{% block content %}
	{% if publications %}
		<div class="special_links">
			<a href="?plain">Plain text</a>,
			<a href="?ris">RIS</a>,
			<a href="?bibtex">BibTex</a>
		</div>
		<h1>{{ list.description }}</h1>
		<hr/>
		{% for publication in publications %}
			<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
				{% include "publications/publication.html" %}
			</div>
		{% endfor %}
	{% else %}
		<h2>Sorry,</h2>
		no publications found for this list.
	{% endif %}
{% endblock %}

publications/templates/publications/publication_authors.html
{% load publication_extras %}
{% if publication.authors %}
	{% if publication.authors_escaped|length > 8 %}
		{% for author, author_escaped in publication.authors_escaped|slice:":8" %}
		<a href="{% url 'publications:author' author_escaped %}" class="author">{{ author }}</a>,
		{% endfor %} <i>et al.</i>
	{% else %}
		{{  publication|authors }}
	{% endif %}<br/>
{% endif %}

publications/templates/publications/publication_detail.html
{% extends "base.html" %}
{% load publication_extras %}

{% block content %}
    <div class="publications-container">
        <h1>{{publication.title}}</h1>
        {% if publication.authors %}
            <p>Authors: {{ publication|authors }}</p>
        {% endif %}
        <p>{% include 'publications/publication.html' %}</p>

        {% if publication.reference_set.count %}
            <h2>References</h2>
            <ul>
                {% for reference in publication.reference_set.all %}
                    <li>
                        {% if reference.locator %}Locator {{ reference.locator}} <i class="fas fa-long-arrow-alt-right"></i> {%endif%}<a href='{{reference.content_object.get_absolute_url}}'>{{reference.content_object}}</a>.
                        <a data-toggle="tooltip" data-placement="bottom" title="Edit" href="{{ reference.get_absolute_update_url}}"><i class="fas fa-edit"></i></a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock content %}

publications/templates/publications/publications.html
{% for publication in publications %}
	<div{% if not forloop.last %} style="margin-bottom: 20px;"{% endif %}>
		{% include "publications/publication.html" %}
	</div>
{% endfor %}

publications/templates/publications/publications_with_thumbnails.html
<table style="width: 100%;">
{% for publication in publications %}
	<tr>
		<td style="width: 100px; padding: 5px 10px 0px 0px; vertical-align: top;">
		{% if publication.thumbnail %}
			{% if publication.code %}
				<a href="{{ publication.code }}"><img src="{{ MEDIA_URL }}{{ publication.thumbnail }}" style="width: 100px; height: 100px;" /></a>
			{% else %}
			<a href="{% url 'publications:id' publication.pk %}"><img src="{{ MEDIA_URL }}{{ publication.thumbnail }}" style="width: 100px; height: 100px;" /></a>
			{% endif %}
		{% endif %}
		</td>
		<td{% if not forloop.last %} style="padding-bottom: 20px; vertical-align: top;"{% endif %}>
			{% include "publications/publication.html" %}
		</td>
	</tr>
{% endfor %}
</table>

publications/templates/publications/reference_add_button.html
{% if perms.publications.add_reference %}
  <a class='btn btn-primary' href='{{ subject.add_ref_url }}' target='_blank'>Add reference</a>
{% endif %}

publications/templates/publications/reference_detail.html
{% extends "base.html" %}
{% load publication_extras %}

{% block content %}
<div class="publications-container">

    <h1>Reference</h1>
    
    <p><a href='{{ reference.content_object.get_absolute_url }}'>{{reference.content_object}}</a></p>
    <p>
        {% publication_authors reference.publication %}
        <a href='{{ reference.publication.get_absolute_url }}'>{{ reference.publication }}</a>{% if reference.locator %}, {{ reference.locator }}{% endif %}.
    </p>
</div>
    
{% endblock content %}

publications/templates/publications/reference_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static i18n compress%}

{% block content %}
    <div class="publications-container">
        {{ form.media.css }}
        <h1>Add Reference</h1>
        <p>Subject: {{ subject }}</p>

        <form method="post">
            <input type="hidden" value="{{ subject.id}}" name="object_id">
            <input type="hidden" value="{{ subject.content_type_id}}" name="content_type">
            {% crispy form %}
        </form>
        {% if request.user.is_staff and admin_url %}
            <a class="btn btn-danger" style="margin-left: 10px;" href="{{admin_url}}">Admin</a>
        {% endif %}

    </div>
{% endblock content %}


{% block script %}
{{ form.media.js }}
{% endblock %}

publications/templates/publications/reference_listing.html
{{ reference.publication }} <a href='{{ reference.publication.get_absolute_url }}'>{{ reference.publication }}</a>{% if reference.locator %}, {{ reference.locator }}{% endif %}.

publications/templates/publications/references_list.html
{% load publication_extras %}
<ol>
  {% for reference in subject.references.all %}
    <li>
      {{ reference.publication.authors }}, <a href='{{ reference.publication.get_absolute_url }}'>{{ reference.publication }}</a>{% if reference.locator %}, {{ reference.locator }}{% endif %}.
    </li>
  {% endfor %}
</ol>
{% reference_add_button subject %}

publications/templates/publications/years.html
{% extends "base.html" %}


{% block content %}
<div class=publications-container>
	<div class="float-right">
        {% if perms.publications.add_publication %}
			<a class="btn btn-primary" data-toggle="tooltip" data-placement="bottom" title="Add" href="{% url 'publications:publication_add' %}">
				<i class="fas fa-plus"></i>
			</a>
		{% endif %}
		<div class="dropdown d-inline-block">
			<button  class="btn btn-primary dropdown-toggle"  type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<i class="fas fa-download fa-sm" ></i>
			</button>
			<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
				<h6 class="dropdown-header">Export</h6>
				<a class="dropdown-item link" href="?plain">Plain text</a>
				<a class="dropdown-item link" href="?ris">RIS</a>
				<a class="dropdown-item link" href="?bibtex">BibTex</a>		
			</div>
		</div>
		
	</div>

	<div>
		{% for year, publications in years %}
			<h2><a href="{% url 'publications:year' year %}">{{ year }}</a></h2>
			<ul>
				{% for publication in publications %}
					<li>
						{% include "publications/publication.html" %}
					</li>
				{% endfor %}
			</ul>
		{% endfor %}
	</div>
</div>
{% endblock %}